/**
 * Shared pure logic for dsh-evolve (mirrors scripts/dsh-evolve.mjs).
 * Kept dependency-free so both the CLI and the plugin use identical
 * extraction/rendering/merge semantics.
 */

import { createHash } from 'node:crypto'
import path from 'node:path'

export function hash(text) {
  return createHash('sha256').update(text).digest('hex').slice(0, 12)
}

const ACTION_RE = /(must|never|always|do not|avoid|required|needs?\b|install|should)/i
const TAG_HINTS = [
  [/install|allowBuilds|pnpm|npm/i, 'install'],
  [/crash|fatal|error|failed/i, 'crash'],
  [/windows|win32/i, 'windows'],
  [/test/i, 'test'],
  [/memory|remember/i, 'memory'],
  [/security/i, 'security'],
  [/perf|performance|efficient/i, 'performance'],
]

export function inferTags(rule) {
  const tags = []
  for (const [re, tag] of TAG_HINTS) {
    if (re.test(rule) && !tags.includes(tag)) tags.push(tag)
  }
  return tags.length > 0 ? tags : ['general']
}

/** Extract deduplicated experience entries from markdown bullets. */
export function extractExperience(markdown, source) {
  const entries = []
  const seen = new Set()
  let n = 0
  for (const raw of markdown.split('\n')) {
    const m = /^\s*[-*]\s+(.+?)\s*$/.exec(raw)
    if (!m) continue
    const rule = m[1].trim().replace(/\s+/g, ' ')
    if (!ACTION_RE.test(rule)) continue
    const key = hash(rule)
    if (seen.has(key)) continue
    seen.add(key)
    n += 1
    entries.push({
      id: `EXP-${String(n).padStart(3, '0')}`,
      rule,
      source,
      tags: inferTags(rule),
      addedAt: new Date().toISOString(),
      verified: null,
      lastVerifiedAt: null,
    })
  }
  return entries
}

const NOISE_RE = /^\s*(warn|info|progress|resolved|added|done|success|ok)\b|resolved \d+|added \d+|done in/i
const ERROR_RE = /(error|failed|fatal|exception|cannot|unable|denied|not found|timeout|ENOENT|ERESOLVE|ERR_|exit code)/i

/** Extract conditional rules from a raw failure log. */
export function extractFromLog(logText, task, source, hint = 'investigate before proceeding') {
  const entries = []
  const seen = new Set()
  let n = 0
  const lines = logText.split('\n')
  for (let i = 0; i < lines.length; i += 1) {
    const line = lines[i].trim()
    if (line === '' || NOISE_RE.test(line) || !ERROR_RE.test(line)) continue
    const rule = `When "${line.slice(0, 160)}" occurs, ${hint}.`
    const key = hash(rule)
    if (seen.has(key)) continue
    seen.add(key)
    n += 1
    entries.push({
      id: `EXP-${String(n).padStart(3, '0')}`,
      rule,
      source: `${source}:${i + 1}`,
      tags: ['log', ...inferTags(line)],
      task,
      addedAt: new Date().toISOString(),
      verified: null,
      lastVerifiedAt: null,
    })
  }
  return entries
}

/** Render entries into an AGENTS.md rules block. */
export function renderRules(entries) {
  const lines = [
    '## Self-evolution rules',
    '',
    '> Auto-generated by dsh-evolve. Rules are traceable to their source and to the last verification run.',
    '',
  ]
  for (const entry of entries) {
    const status = entry.verified === true ? '✅ verified'
      : entry.verified === false ? '❌ verification failed'
        : '○ unverified'
    lines.push(`- [${entry.id}] ${entry.rule} _(source: ${entry.source} · ${status}${entry.lastVerifiedAt ? ' · ' + entry.lastVerifiedAt.slice(0, 10) : ''})_`)
  }
  lines.push('')
  return lines.join('\n')
}

/** dsh profile paths (respects DSH_HOME, defaults ~/.dsh). */
export function profileRoot(profile) {
  const home = process.env.DSH_HOME ?? path.join(process.env.USERPROFILE ?? process.env.HOME ?? '.', '.dsh')
  return path.join(home, 'profiles', profile)
}

export function profileAgentsPath(profile) {
  return path.join(profileRoot(profile), 'AGENTS.md')
}

export function profileDataPath(profile) {
  return path.join(profileRoot(profile), 'data', 'dsh-evolve', 'experience.jsonl')
}

/** Replace the previous rules block, or append. */
export function mergeRules(existing, rendered) {
  const marker = '## Self-evolution rules'
  const idx = existing.indexOf(marker)
  if (idx === -1) {
    return `${existing.replace(/\s*$/, '')}\n\n${rendered.trim()}\n`
  }
  const next = existing.indexOf('\n## ', idx + marker.length)
  const block = next === -1 ? existing.slice(idx) : existing.slice(idx, next)
  return existing.replace(block, `${rendered.trim()}\n`)
}

/** Jaccard similarity over word bigrams. */
export function ruleSimilarity(a, b) {
  const grams = (s) => {
    const words = s.toLowerCase().split(/\W+/).filter((w) => w.length > 2)
    const set = new Set()
    for (let i = 0; i < words.length - 1; i += 1) set.add(`${words[i]} ${words[i + 1]}`)
    return set
  }
  const ga = grams(a)
  const gb = grams(b)
  if (ga.size === 0 || gb.size === 0) return 0
  let inter = 0
  for (const g of ga) if (gb.has(g)) inter += 1
  return inter / new Set([...ga, ...gb]).size
}

export function auditRules(entries, threshold = 0.7) {
  const byTag = {}
  const bySource = {}
  const duplicates = []
  for (const e of entries) {
    for (const tag of e.tags ?? []) byTag[tag] = (byTag[tag] ?? 0) + 1
    bySource[e.source] = (bySource[e.source] ?? 0) + 1
  }
  for (let i = 0; i < entries.length; i += 1) {
    for (let j = i + 1; j < entries.length; j += 1) {
      if (ruleSimilarity(entries[i].rule, entries[j].rule) >= threshold) {
        duplicates.push([entries[i].id, entries[j].id])
      }
    }
  }
  return {
    total: entries.length,
    verified: entries.filter((e) => e.verified === true).length,
    unverified: entries.filter((e) => e.verified !== true).length,
    byTag,
    bySource,
    duplicates,
  }
}
